### ISSUE TITLE
training batch size

### ISSUE THREAD

**Issue by futianfan** [lucidrains/egnn-pytorch#26]
Dear authors, 

thanks for your great work! I saw your example, which is easy to understand. But I notice that during training, in each iteration,  it seems it supports the case where batch-size > 1, but all the graphs have the same adj_mat.  do you have better solution for that? thanks

**Comment by hypnopump** [comment]
Hi there! We hope you're using this package for something interesting ;)

We built this equivariant graph neural network with the goal of serving as a cheaper structure refiner in the AlphaFold2 replication ( https://github.com/lucidrains/alphafold2 ). That's the main reason for the tests being with a protein dataset and the adjacency matrix looking similar between proteins (only backbone atoms are considered to neighbours due to covalent bonds), although they aren't, since proteins vary in length.

As for the batch size, the best current setup requires the `GRADIENT_ACCUMULATE_EVERY` param to be modified according to the user's needs (keep in mind this is a graph neural network, so training cost should not be very high even for this setup). 

Currently, there's 2 versions of the network / layer: one using pure pytorch (the one in the examples) and one using the pytorch geometric library (the layer is names `EGNN_sparse`). If you're using the pytorch one, you should have no problem passing a batch directly to the network, as long as the data has the same dimensions. If you're using the pytorch geometric one, however, you could load the data from a pytorch geometric dataloader (which merges different graphs into one disconnected graph , as explained here: https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html?highlight=dataloader#torch_geometric.data.DataLoader ) to fully utilize the gpu. Either way, you can also use the `GRADIENT_ACCUMULATE_EVERY` setup.

Hope this helps!

**Comment by futianfan** [comment]
thanks for your response. i did not use egnn for protein application. i use the example in the readme, using class EGNN_Network. and want to know how to feedforward different ``adj_mat``s.  thanks

**Comment by futianfan** [comment]
suppose in current batch, i have 3 graphs, whose node number is n1,n2,n3, respectively, then I set ``adj_mat`` to a (3,n,n) tensor, where n=max(n1,n2,n3).   

does it work?

**Comment by hypnopump** [comment]
Hmm so you could either pass 1 adj_mat and 1 graph, then to `GRADIENT_ACCUMULATE_EVERY=3`, or pass the 3 adj_mats directly along the 3 graphs (it should work, although i havent tested it. If it doesn't, please tell us and we'll correct it!)

**Comment by futianfan** [comment]
it did not cause an error. I assumed it works.

**Comment by futianfan** [comment]
thanks for your time and help!
