### ISSUE TITLE
About aggregations in EGNN_sparse

### ISSUE THREAD

**Issue by simon1727** [lucidrains/egnn-pytorch#28]
Hi, thanks for your great work!

I have a question on how aggregations are computed for node embedding and coordinate embedding. In the paper, the aggregation for node embedding is computed over its neighbors, while the aggregation for coordinate embedding is computed over is computed over all others. However, in EGNN_sparse, I didn't notice such difference in aggregations.

I guess it is because computing all-pair messages for coordinate embedding makes 'sparse' meaningless, but I would like to double-check to see if I get this correctly. So anyway, did you do this intentionally? Or did I miss something?

My appreciation.

**Comment by hypnopump** [comment]
Hi there!  We are always glad to see the code is being used. 

So for the sparse aggregation: if you look at the table in the readme, the `m_hat_i` that is used for coordinates aggregation actually depends on the `m_hat_ij`, which in turn depends on the `m_ij`. That's why we only update the coordinates based on the neighbours positions, since we don't have the `m_ij` for the other points (this design was a personal license since the official code is not released as far as I know, but it made sense to do it this way because otherwise it would not be a "sparse implementation", but rather a "sparse feature update"). 

A cool thing you could try is comparing both options (the current one and the coordinates update based on the whole point cloud) and see if the results are any different / better. Either way, we're planning on applying this method to alphafold2, and would be nice to hear corroboration that it works (for any application you might have in mind)!

**Comment by simon1727** [comment]
Hi hypnopump. Yes I agree that update coordinate based on the whole set is inconsistent to "sparse implementation". Guess I will be using the standard EGNN as I am working on rather small dataset, but it sounds cool to also experiment on the sparse EGNN to see the difference!

Thanks a lot for your reply!

**Comment by hypnopump** [comment]
Hi there! 
Did you noticed any difference on the implementation / expected working ? I'm wondering if I should include the full aggregation option you mentioned somehow...

**Comment by simon1727** [comment]
> Hi there!
> Did you noticed any difference on the implementation / expected working ? I'm wondering if I should include the full aggregation option you mentioned somehow...

Hi! I employed the full aggregation one and it works fine, but I have not experimented on the sparse one yet.
